WARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:149 Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): operation timed out
INFO     Test_user_login:test_user_login_params.py:19 Testcase 'test_login_with_params' Started
INFO     Test_user_login:test_user_login_params.py:20 Opening the Browser
INFO     Test_user_login:test_user_login_params.py:22 Assigning Variable to Login Page
INFO     Test_user_login:test_user_login_params.py:24 Entering Email from Params -->admin@yourstore.com1
INFO     Test_user_login:test_user_login_params.py:26 Entering Password from Params -->admin
INFO     Test_user_login:test_user_login_params.py:28 Clicking on Login Button
INFO     Test_user_login:test_user_login_params.py:30 Updating List
INFO     Test_user_login:test_user_login_params.py:45 Entered into 'outer elif' block
INFO     Test_user_login:test_user_login_params.py:47 Entered into 'inner if block' of 'outer elif block' -->fail
INFO     Test_user_login:test_user_login_params.py:48 Appending the list
INFO     Test_user_login:test_user_login_params.py:54 Printing the list
INFO     Test_user_login:test_user_login_params.py:57 Testcase 'test_login_with_params' has Passed
INFO     Test_user_login:test_user_login_params.py:58 Capturing Screenshot for Allure Report
INFO     Test_user_login:test_user_login_params.py:68 Testcase 'test_login_with_params' has Completed